name: NodeJS CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install --global yarn
      - run: npm config set always-auth true
      - run: echo '//npm.pkg.github.com/:_authToken=${{ secrets.REGISTRY_TOKEN }}' >> .npmrc
      - run: yarn install
      - run: yarn run build
